language: node_js
env:
  global:
    - DISPLAY=:99.0

node_js:
  - node
  - 'lts/*'

addons:
  chrome: stable

services:
  - xvfb

cache: npm

jobs:
  include:
    - stage: Lint
      node_js: node
      script: npm run lint
    - stage: Test Unit
      node_js: node
      script: npm run test:unit
